<!-- // BEGIN // Banana Stand Integration code. See https://www.fera.ai for more information. -->
    <script>
      window.__bsio = window.__bsio || []; window.__bsioDebugMode = true;
      window.__bsio.push({
        action: "configure",
        data: { store_pk: "<?php echo Mage::helper('banana')->getPublicKey(); ?>", api_url: "<?php echo Mage::helper('banana')->getApiUrl(); ?>" }
      });
      window.__bsio.push({ action: "setCustomerId", customer_id: "<?php echo Mage::getSingleton('customer/session')->getCustomerId(); ?>" });
      window.__bsio.push({ action: "loadPlatformAdapter", code: "magento" });
      window.__bsio.push({ action: 'setCart', cart: { items: <?php echo Mage::helper('banana')->getCartJson(); ?> }});
    </script>
    <?php echo $this->getChildHtml('bananastand.footer.product.view'); ?>
    <?php echo $this->getChildHtml('bananastand.footer.checkout.success'); ?>
    <script async type="application/javascript" src="<?php echo Mage::helper('banana')->getJsUrl(); ?>"></script>
<!--// END Banana Stand integration code. //-->
