
<!-- This code initializes the banana stand script: -->
<script>
  window.__bsio = window.__bsio || [];
  window.__bsio.push({
    action: "configure",
    data: { store_pk: "<?php echo Mage::helper('banana')->getPublicKey(); ?>", api_url: "<?php echo Mage::helper('banana')->getApiUrl(); ?>" }
  });
  window.__bsio.push({ action: "setCustomerId", customer_id: "<?php echo Mage::getSingleton('customer/session')->getCustomerId(); ?>" });
  window.__bsio.push({ action: "loadPlatformAdapter", code: "magento" })
</script>
<script async type="application/javascript" src="<?php echo Mage::helper('banana')->getJsUrl(); ?>"></script>
<!--// END Banana Stand integration code. //-->
