<!--// BEGIN Fera.ai Integration Code //-->
    <script>
      window.__bsio = window.__bsio || [];
      <?php echo Mage::helper('aiconnector')->getDebugJs(), PHP_EOL;?>
      window.__bsio.push({
        action: "configure",
        data: { store_pk: "<?php echo Mage::helper('aiconnector')->getPublicKey(); ?>", api_url: "<?php echo Mage::helper('aiconnector')->getApiUrl(); ?>" }
      });
      window.__bsio.push({ action: "setCustomerId", customer_id: "<?php echo Mage::getSingleton('customer/session')->getCustomerId(); ?>" });
      window.__bsio.push({ action: "loadPlatformAdapter", code: "magento" });
      window.__bsio.push({ action: 'setCart', cart: { items: <?php echo Mage::helper('aiconnector')->getCartJson(); ?> }});
    </script>
    <?php echo $this->getChildHtml('aiconnector.footer.product.view'); ?>
    <?php echo $this->getChildHtml('aiconnector.footer.checkout.success'); ?>
    <script async type="application/javascript" src="<?php echo Mage::helper('aiconnector')->getJsUrl(); ?>"></script>
<!--// END Fera.ai Integration Code //-->
